In [1]:
## using the same matrix for addition ,multiplication and transpose

In [2]:
import numpy as np
mat_1 = np.array([[1,2],[3,4]])
mat_2 = np.array([[5,6],[7,8]])

In [6]:
## Question 1
print(np.add(mat_1,mat_2)) ##addition of two matrices

[[ 6  8]
 [10 12]]


In [8]:
##Question 2
print(np.multiply(mat_1,mat_2)) ##multiplication of two matrices

[[ 5 12]
 [21 32]]


In [10]:
##Question 3
print(mat_1.T) ## transpose of first matrice

[[1 3]
 [2 4]]


In [11]:
print(mat_2.T) ## transpose of second matrice

[[5 7]
 [6 8]]


In [21]:
##Question 4
def sort(s):
    a = s.split()
    for i in range(len(a)):
        a[i] = a[i].lower()
    a.sort()
    
    return ' '.join(a)

In [22]:
s = 'Ineuron is an online learning website'
sort(s)

'an ineuron is learning online website'

In [28]:
##Question 5
test_str = "Gfg, is best : for ! cscjcinscbc ;"
print("The original string is : " + test_str)
punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
for ele in test_str:
    if ele in punc:
        test_str = test_str.replace(ele, "")
print("The string after punctuation filter : " + test_str)

The original string is : Gfg, is best : for ! cscjcinscbc ;
The string after punctuation filter : Gfg is best  for  cscjcinscbc 
